version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_DATABASE: 'MapaVirtual'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
  web1:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - '8001:8000'
    depends_on: 
    - db
    links: 
    - db
  web2:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - '8002:8000'
    depends_on: 
    - db
    links: 
    - db
  web3:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - '8000:8000'
    depends_on: 
    - db
    links: 
    - db
  
  nginx:
    image: nginx
    ports:
      - 8005:8000
    


      