# Generated by Django 3.1 on 2020-08-21 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camposanto',
            fields=[
                ('id_camposanto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=15, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('correo', models.CharField(max_length=70, unique=True)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('direccion_matriz', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_difunto',
            fields=[
                ('id_responsable', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('telefono', models.CharField(default=None, max_length=10)),
                ('celular', models.CharField(default=None, max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('parentezco', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('usuario', models.CharField(max_length=10, unique=True)),
                ('contrasena', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=10)),
                ('genero', models.CharField(default=None, max_length=15)),
                ('direccion', models.CharField(default=None, max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('id_camposanto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.camposanto')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_sepultura',
            fields=[
                ('id_tip_sepultura', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=15, unique=True)),
                ('descripcion', models.CharField(max_length=70, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_camposanto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.camposanto')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=15, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_camposanto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.camposanto')),
            ],
        ),
        migrations.CreateModel(
            name='Red_social',
            fields=[
                ('id_red_social', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=15, unique=True)),
                ('link', models.CharField(max_length=70)),
                ('estado', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Punto_geolocalizacion',
            fields=[
                ('id_punto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('latitud', models.FloatField()),
                ('longintud', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('id_camposanto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.camposanto')),
            ],
        ),
        migrations.CreateModel(
            name='Difunto',
            fields=[
                ('id_difunto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=10)),
                ('lugar_nacimiento', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_difuncion', models.CharField(max_length=40)),
                ('fecha_difuncion', models.DateField()),
                ('no_lapida', models.CharField(max_length=15)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('num_rosas', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_camposanto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.camposanto')),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.responsable_difunto')),
                ('id_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.sector')),
                ('id_tip_sepultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.tipo_sepultura')),
            ],
        ),
        migrations.AddField(
            model_name='camposanto',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.empresa'),
        ),
    ]
