# Generated by Django 3.1 on 2021-01-15 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=200, null=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('image_perfil', models.ImageField(blank=True, default=None, max_length=500, null=True, upload_to='perfil')),
                ('is_facebook', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('genero', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('tipo_usuario', models.CharField(choices=[('su', 'super_admin'), ('ad', 'admin'), ('uf', 'usuario_final'), ('ha', 'hiper_admin')], default='ad', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, max_length=500, null=True, upload_to='sugerencias')),
                ('mensaje', models.CharField(max_length=500)),
                ('fecha_emision', models.DateField()),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='H_audio',
            fields=[
                ('id_audio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mensaje', models.CharField(max_length=200)),
                ('audio', models.FileField(blank=True, max_length=200, null=True, upload_to='h_audio')),
            ],
        ),
        migrations.CreateModel(
            name='H_imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mensaje', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='h_imagen')),
            ],
        ),
        migrations.CreateModel(
            name='H_mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mensaje', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='H_video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mensaje', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, max_length=200, null=True, upload_to='h_video')),
            ],
        ),
        migrations.CreateModel(
            name='H_youtube',
            fields=[
                ('id_youtube', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mensaje', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_rosas',
            fields=[
                ('id_rosa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rosa', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Homenajes',
            fields=[
                ('id_homenaje', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_publicacion', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
                ('gratuito', models.BooleanField(default=True)),
                ('id_audiocontent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_audio')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=70)),
                ('mensaje', models.CharField(max_length=500)),
                ('fecha_created', models.DateField()),
                ('estado', models.CharField(choices=[('enviada', 'enviada'), ('no_enviada', 'no_enviada')], default='no_enviada', max_length=40)),
                ('tipo', models.CharField(choices=[('paquete', 'paquete'), ('tip', 'tip')], default='tip', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='paquetes')),
                ('fecha_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TokenDevice',
            fields=[
                ('id_token_device', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('token_device', models.CharField(max_length=1500)),
                ('plataform', models.CharField(blank=True, default=None, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_permisos',
            fields=[
                ('id_user_permiso', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.permiso')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='punto_geolocalizacion',
            old_name='longintud',
            new_name='longitud',
        ),
        migrations.RemoveField(
            model_name='difunto',
            name='id_responsable',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='red_social',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='camposanto',
            name='logo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='difunto',
            name='cedula',
            field=models.CharField(default=994160253, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='web',
            field=models.CharField(default='w', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='red_social',
            name='id_camposanto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.camposanto'),
        ),
        migrations.AddField(
            model_name='responsable_difunto',
            name='id_difunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciosBackend.difunto'),
        ),
        migrations.AlterField(
            model_name='camposanto',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.empresa'),
        ),
        migrations.AlterField(
            model_name='camposanto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='lugar_difuncion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='lugar_nacimiento',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='no_lapida',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='num_rosas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='punto_geolocalizacion',
            name='id_camposanto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.camposanto'),
        ),
        migrations.AlterField(
            model_name='red_social',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='red_social',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='responsable_difunto',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='responsable_difunto',
            name='celular',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='responsable_difunto',
            name='correo',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responsable_difunto',
            name='direccion',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responsable_difunto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='responsable_difunto',
            name='parentezco',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='responsable_difunto',
            name='telefono',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipo_sepultura',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo_sepultura',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='tokendevice',
            name='id_camposanto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.camposanto'),
        ),
        migrations.AddField(
            model_name='tokendevice',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paquetes',
            name='id_camposanto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.camposanto'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='id_camposanto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.camposanto'),
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_difunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.difunto'),
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_imagecontent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_imagen'),
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_textcontent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_mensaje'),
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_videocontent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_video'),
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_youtube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_youtube'),
        ),
        migrations.AddField(
            model_name='historial_rosas',
            name='id_difunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.difunto'),
        ),
        migrations.AddField(
            model_name='historial_rosas',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='id_difunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.difunto'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacto',
            name='id_camposanto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.camposanto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='id_camposanto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciosBackend.camposanto'),
        ),
    ]
