# Generated by Django 3.1 on 2020-08-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='red_social',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='red_social',
            name='id_camposanto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.camposanto'),
        ),
        migrations.AlterField(
            model_name='camposanto',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciosBackend.empresa'),
        ),
        migrations.AlterField(
            model_name='camposanto',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
