# Generated by Django 3.1 on 2020-08-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0003_auto_20200821_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difunto',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='lugar_difuncion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='lugar_nacimiento',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='no_lapida',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='difunto',
            name='num_rosas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='responsable_difunto',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='responsable_difunto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tipo_sepultura',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo_sepultura',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
