# Generated by Django 3.1 on 2020-08-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0004_auto_20200821_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difunto',
            name='id_responsable',
        ),
        migrations.AddField(
            model_name='responsable_difunto',
            name='id_difunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviciosBackend.difunto'),
        ),
    ]
