# Generated by Django 3.1 on 2020-08-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0007_auto_20200821_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
        migrations.AddField(
            model_name='camposanto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
