# Generated by Django 3.1 on 2020-08-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0007_auto_20200821_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='web',
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
