# Generated by Django 3.1 on 2020-08-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0008_auto_20200822_0022'),
        ('serviciosBackend', '0008_empresa_web'),
    ]

    operations = [
    ]
