# Generated by Django 3.1 on 2020-08-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0011_auto_20200822_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='difunto',
            name='cedula',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
