# Generated by Django 3.1 on 2020-08-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0012_auto_20200822_1607'),
        ('serviciosBackend', '0012_difunto_cedula'),
    ]

    operations = [
    ]
