# Generated by Django 3.1 on 2020-08-23 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0014_auto_20200822_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camposanto',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviciosBackend.empresa'),
        ),
    ]
