# Generated by Django 3.1 on 2020-08-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0032_user_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='superuser',
            new_name='super_u',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('su', 'super_admin'), ('ad', 'admin'), ('uf', 'usuario_final'), ('ha', 'hiper_admin')], default='ad', max_length=30),
        ),
    ]
