# Generated by Django 3.1 on 2020-08-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0033_auto_20200825_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='super_u',
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('su', 'super_admin'), ('ad', 'admin'), ('uf', 'usuario_final'), ('ha', 'hiper_admin')], default='ad', max_length=40),
        ),
    ]
