# Generated by Django 3.1 on 2020-08-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0037_auto_20200827_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
