# Generated by Django 3.1 on 2020-09-23 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0041_auto_20200922_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='responsable_difunto',
            name='direccion',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='User_permisos',
            fields=[
                ('id_user_permiso', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.permiso')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
