# Generated by Django 3.1 on 2020-10-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0044_user_is_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=200, null=True, verbose_name='email address'),
        ),
    ]
