# Generated by Django 3.1 on 2020-10-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0045_auto_20201001_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homenaje',
            fields=[
                ('id_homenaje', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='imagen')),
                ('video', models.FileField(blank=True, max_length=200, null=True, upload_to='h_video')),
                ('audio', models.FileField(blank=True, max_length=200, null=True, upload_to='h_audio')),
            ],
        ),
    ]
