# Generated by Django 3.1 on 2020-10-03 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0045_auto_20201001_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homenajes',
            fields=[
                ('id_homenaje', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_publicacion', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('likes', models.IntegerField(default=0)),
                ('id_difunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.difunto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='H_video',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mensaje', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, max_length=200, null=True, upload_to='h_video')),
                ('id_homenaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.homenajes')),
            ],
        ),
        migrations.CreateModel(
            name='H_mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mensaje', models.CharField(max_length=1500)),
                ('id_homenaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.homenajes')),
            ],
        ),
        migrations.CreateModel(
            name='H_imagen',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mensaje', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='h_imagen')),
                ('id_homenaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.homenajes')),
            ],
        ),
    ]
