# Generated by Django 3.1 on 2020-10-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0046_h_imagen_h_mensaje_h_video_homenajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='h_imagen',
            name='id_homenaje',
        ),
        migrations.RemoveField(
            model_name='h_mensaje',
            name='id_homenaje',
        ),
        migrations.RemoveField(
            model_name='h_video',
            name='id_homenaje',
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_imagecontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_imagen'),
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_textcontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_mensaje'),
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_videocontent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_video'),
        ),
    ]
