# Generated by Django 3.1 on 2020-11-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0046_homenaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_perfil',
            field=models.ImageField(blank=True, default=None, max_length=500, null=True, upload_to='perfil'),
        ),
    ]
