# Generated by Django 3.1 on 2020-10-03 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0047_auto_20201003_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenajes',
            name='id_imagecontent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_imagen'),
        ),
        migrations.AlterField(
            model_name='homenajes',
            name='id_textcontent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_mensaje'),
        ),
        migrations.AlterField(
            model_name='homenajes',
            name='id_videocontent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_video'),
        ),
    ]
