# Generated by Django 3.1 on 2020-10-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0048_auto_20201003_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='h_imagen',
            old_name='id_mensaje',
            new_name='id_imagen',
        ),
        migrations.RenameField(
            model_name='h_video',
            old_name='id_mensaje',
            new_name='id_video',
        ),
    ]
