# Generated by Django 3.1 on 2020-10-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0051_historial_rosas_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='H_audio',
            fields=[
                ('id_audio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mensaje', models.CharField(max_length=200)),
                ('audio', models.FileField(blank=True, max_length=200, null=True, upload_to='h_audio')),
            ],
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_audiocontent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_audio'),
        ),
    ]
