# Generated by Django 3.1 on 2020-10-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0043_auto_20200929_1932'),
        ('serviciosBackend', '0052_auto_20201008_1819'),
    ]

    operations = [
    ]
