# Generated by Django 3.1 on 2020-11-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0048_auto_20201101_1947'),
        ('serviciosBackend', '0053_merge_20201012_2229'),
    ]

    operations = [
    ]
