# Generated by Django 3.1 on 2020-11-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0054_merge_20201110_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homenaje',
        ),
    ]
