# Generated by Django 3.1 on 2020-11-14 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0055_delete_homenaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDevice',
            fields=[
                ('id_token_device', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('token_device', models.CharField(max_length=1500)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
