# Generated by Django 3.1 on 2020-11-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0056_tokendevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendevice',
            name='plataform',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
