# Generated by Django 3.1 on 2020-11-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0058_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritos',
            name='estado',
        ),
        migrations.AlterField(
            model_name='historial_rosas',
            name='fecha_publicacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='homenajes',
            name='fecha_publicacion',
            field=models.DateTimeField(),
        ),
    ]
