# Generated by Django 3.1 on 2020-12-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0060_paquetes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquetes',
            name='estado',
        ),
    ]
