# Generated by Django 3.1 on 2020-12-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0061_remove_paquetes_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
