# Generated by Django 3.1 on 2020-12-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0064_auto_20201212_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='estado',
            field=models.CharField(choices=[('enviada', 'enviada'), ('no_enviada', 'no_enviada')], default='no_enviada', max_length=40),
        ),
    ]
