# Generated by Django 3.1 on 2020-12-30 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0066_tokendevice_id_camposanto'),
    ]

    operations = [
        migrations.CreateModel(
            name='H_youtube',
            fields=[
                ('id_youtube', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mensaje', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='homenajes',
            name='likes',
        ),
        migrations.AddField(
            model_name='homenajes',
            name='gratuito',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, max_length=500, null=True, upload_to='sugerencias')),
                ('mensaje', models.CharField(max_length=500)),
                ('fecha_emision', models.DateField()),
                ('id_camposanto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.camposanto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homenajes',
            name='id_youtube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviciosBackend.h_youtube'),
        ),
    ]
