# Generated by Django 3.1 on 2020-12-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0067_auto_20201228_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='imagen',
        ),
    ]
