# Generated by Django 3.1 on 2020-12-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0068_remove_contacto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='sugerencias'),
        ),
    ]
