# Generated by Django 3.1 on 2020-12-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosBackend', '0069_contacto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='imagen',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='sugerencias'),
        ),
    ]
